### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by kayhantolga** [cgillum/azure-functions-openai-extension#1]
Library Update
please use the newer version of Betalgo.OpenAI
`<PackageReference Include="Betalgo.OpenAI" Version="6.8.*" />`
https://github.com/cgillum/azure-functions-openai-extension/blob/5ab029eb8e664ef86d1d63c7336607ebf5ecd3b4/sandbox/OpenAITesting/OpenAITesting.csproj#L11

**Comment by cgillum** [comment]
Done as part of https://github.com/cgillum/azure-functions-openai-extension/commit/4813ae2dd50156069b6ce03dece5cf055a2ac2c9
