### ISSUE TITLE
Question about textCompletion input binding format

### ISSUE THREAD

**Issue by georgeOsdDev** [cgillum/azure-functions-openai-extension#27]
textCompletion input binding give JSON with CapitalizedCase keys. eg: `Choices`.
Is this expected behavior?
This cause error with sample code.

<img width="997" alt="image" src="https://github.com/cgillum/azure-functions-openai-extension/assets/1381907/3da783ce-8d8e-40d8-b06d-fc7bfb879e8c">

**Comment by manvkaur** [comment]
Thank you @georgeOsdDev for reporting this issue. This issue is fixed in Microsoft repo - visit the [Azure/azure-functions-openai-extension](https://github.com/Azure/azure-functions-openai-extension/) to learn more or make contributions.
